Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2022-11, with the labels that each got.

#292 2434 Spring Tomcat CVE's
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-292

#297 fortify fix
  charts/am-role-assignment-refresh-batch/values.preview.template.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-297

#320 Update Jenkinsfile_CNP
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-320
