Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2022-09, with the labels that each got.

#248 update postgres version
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-248

#250 AM-2343 Suppressing LD SnakeYaml CVE
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-250

#253 2380_CVE
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-253

#254 Suppressing snakeyaml additional CVE
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-254
