Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2022-10, with the labels that each got.

#255 CVE issues and build failures
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-255

#256 Jackson CVE-2022-42003
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-256

#258 Update renovate.json
  renovate.json
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-258

#281 fortify scan fix
  Dockerfile
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-281
