Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2022-01, with the labels that each got.

#131 Update fortify release id
  Jenkinsfile_CNP
  Jenkinsfile_nightly_disabled
  config/fortify-client.properties
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-131

#144 Enable nightly build and implement fortify
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-144

#145 Removing jcenter
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-145
