Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2022-04, with the labels that each got.

#184 Updated postgres dependency
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-184

#197 cve fix
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-197

#198 Add combine pull request action
  .github/workflows/combine-prs.yml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-198

#200 CVE fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-200

#201 CVE fix
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-201

#202 cve fix
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-202

#203 CVE fix
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-203
