Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2022-05, with the labels that each got.

#204 AM-2138: Upgrading to Java 17
  Dockerfile
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-204

#231 Update combine-prs.yml for renovate
  .github/workflows/combine-prs.yml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-231

#235 Delete dependabot.yml
  .github/dependabot.yml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-235

#236 Update suppressions.xml
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-236

#237 CVE-2016-1000027 suppression
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-237

#238 Upgrade tomcat
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-238
