Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2023-05, with the labels that each got.

#485 AM-2786 CVE-2023-20873 AM-2787 CVE-2023-20862
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-485

#488 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-488

#489 nightly cron timing corrected
  Jenkinsfile_nightly
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-489

#490 AM-2816 CVE-2023-28709 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-490

#492 AM-2806: Upgrade chart-job version
  charts/am-role-assignment-refresh-batch/Chart.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-492

#491 AM-2816 CVE-2023-28709 tomcat version upgraded to 9.0.74
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-491
