Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2023-07, with the labels that each got.

#499 AM-2846: For preview pipelines enable cleanup of helm releases
  Jenkinsfile_CNP
Labels: ns:am, prd:am, keep-helm, rel:am-role-assignment-refresh-batch-pr-499

#494 AM-2823-CVE-2023-20883 FIX
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-494

#500 AM-2852 CVE-2023-34981 tomcat upgrade 9.0.76
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-500

#503 AM-2728 CVE-2022-1471 snakeyaml 2.0
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-503

#504 AM-2728 AM-2860 Remove Github Autoupdate
  .github/workflows/autoupdate.yml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-504

#508 AM-2851 CVE-2023-2976 guava 32.0.1-jre, suppression removed
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-508

#526 AM-2883 CVE-2023-34035 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-526

#531 AM-2888 CVE-2023-34034 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-531
