Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2023-02, with the labels that each got.

#396 dependency check
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-396

#406 S2s Client version
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-406

#407 springboot upgrade 2.7.7
  build.gradle
  charts/am-role-assignment-refresh-batch/Chart.yaml
  config/owasp/suppressions.xml
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-407

#426 RAS-Refresh:Application Nightly build failed due to CVE-2022-45688
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-426
