Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2023-03, with the labels that each got.

#437 ORM and Refresh Batch-Application Nightly Build failed
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-437

#440 masterbuildfailure
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-440

#447 Revert "Renovate Combined Pull Request"
  build.gradle
  infrastructure/.terraform-version
  infrastructure/terraform.tf
Labels: ns:am, prd:am, no-changes, rel:am-role-assignment-refresh-batch-pr-447
