Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2023-09, with the labels that each got.

#558 AM-2923 CVE-2023-41080 Suppression
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-558

#561 AM-2924 Remove keep-helm
  Jenkinsfile_CNP
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-561, enable_keep_helm

#565 AM-2923 CVE-2023-41080 tomcat upgraded to 9.0.80, suppression removed
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-565

#568 Am 2927
  build.gradle
  src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/feignclients/configuration/FeignClientInterceptor.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/task/RefreshORMRules.java
  src/main/resources/application.yaml
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-568

#564 AM-2921 Update Renovate Config
  renovate.json
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-564
