Repository hmcts/am-role-assignment-refresh-batch, pull requests merged in 2024-06, with the labels that each got.

#785 DTSAM-350 Deprecation of properties-volume-spring-boot-starter - grad…
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-785

#789 Test alternative sonarqube config for #788
  build.gradle
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-789

#788 DTSAM-319 Refactor calls to RAS User Count
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/roleassignmentrefresh/domain/service/process/RefreshJobsOrchestratorIntegrationTest.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/advice/exception/ForbiddenException.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/constants/RefreshConstants.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/domain/service/process/RefreshJobsOrchestrator.java
  src/main/java/uk/gov/hmcts/reform/roleassignmentrefresh/oidc/IdamRepository.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/roleassignmentrefresh/domain/service/process/RefreshJobsOrchestratorTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignmentrefresh/launchdarkly/FeatureConditionEvaluatorTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignmentrefresh/oidc/IdamRepositoryTest.java
  src/test/java/uk/gov/hmcts/reform/roleassignmentrefresh/oidc/SecurityUtilsTest.java
Labels: ns:am, prd:am, rel:am-role-assignment-refresh-batch-pr-788
